"""model change

Revision ID: 97fdd1bef659
Revises: bf80c6223ed4
Created: 2026-08-06 17:20:12.101286+00:00

GENERATED by `alembic revision --autogenerate`. Read it before applying
it — autogenerate is very good at additions and notoriously literal about
renames, which it sees as a DROP and an ADD. Dropping a column takes the
data in it with it.
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '97fdd1bef659'
down_revision: Union[str, None] = 'bf80c6223ed4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enquiry',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('handled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('handled_by_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['handled_by_id'], ['member.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_enquiry_token'), 'enquiry', ['token'], unique=True)
    op.create_table('enquiry_message',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('enquiry_id', sa.UUID(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['enquiry_id'], ['enquiry.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_enquiry_message_enquiry_id'), 'enquiry_message', ['enquiry_id'], unique=False)
    op.add_column('member', sa.Column('can_answer', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('member', 'can_answer')
    op.drop_index(op.f('ix_enquiry_message_enquiry_id'), table_name='enquiry_message')
    op.drop_table('enquiry_message')
    op.drop_index(op.f('ix_enquiry_token'), table_name='enquiry')
    op.drop_table('enquiry')
    # ### end Alembic commands ###
