"""model change

Revision ID: bf80c6223ed4
Revises: 1586cb2b805f
Created: 2026-08-05 23:31:41.069614+00:00

GENERATED by `alembic revision --autogenerate`. Read it before applying
it — autogenerate is very good at additions and notoriously literal about
renames, which it sees as a DROP and an ADD. Dropping a column takes the
data in it with it.
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'bf80c6223ed4'
down_revision: Union[str, None] = '1586cb2b805f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('member_id', sa.UUID(), nullable=False),
    sa.Column('purpose', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['member.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_token_expires_at'), 'token', ['expires_at'], unique=False)
    op.create_index(op.f('ix_token_member_id'), 'token', ['member_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_token_member_id'), table_name='token')
    op.drop_index(op.f('ix_token_expires_at'), table_name='token')
    op.drop_table('token')
    # ### end Alembic commands ###
