"""model change

Revision ID: dbc9ad33aa51
Revises: a5801cef0ec3
Created: 2026-08-05 13:23:00.849504+00:00

GENERATED by `alembic revision --autogenerate`. Read it before applying
it — autogenerate is very good at additions and notoriously literal about
renames, which it sees as a DROP and an ADD. Dropping a column takes the
data in it with it.
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'dbc9ad33aa51'
down_revision: Union[str, None] = 'a5801cef0ec3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('identity', 'email')
    op.drop_column('member', 'last_login_at')
    op.drop_column('member', 'display_name')
    op.drop_column('session', 'user_agent')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session', sa.Column('user_agent', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.add_column('member', sa.Column('display_name', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.add_column('member', sa.Column('last_login_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('identity', sa.Column('email', sa.VARCHAR(length=320), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
