"""members, identities and sessions

Revision ID: a5801cef0ec3
Revises: 
Created: 2026-08-05 13:14:13.151723+00:00

GENERATED by `alembic revision --autogenerate`. Read it before applying
it — autogenerate is very good at additions and notoriously literal about
renames, which it sees as a DROP and an ADD. Dropping a column takes the
data in it with it.
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a5801cef0ec3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('member',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_approved', sa.Boolean(), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_member_email'), 'member', ['email'], unique=True)
    op.create_table('identity',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('member_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['member.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'subject', name='uq_identity_provider_subject')
    )
    op.create_index(op.f('ix_identity_member_id'), 'identity', ['member_id'], unique=False)
    op.create_table('session',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('member_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_agent', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['member.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_expires_at'), 'session', ['expires_at'], unique=False)
    op.create_index(op.f('ix_session_member_id'), 'session', ['member_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_session_member_id'), table_name='session')
    op.drop_index(op.f('ix_session_expires_at'), table_name='session')
    op.drop_table('session')
    op.drop_index(op.f('ix_identity_member_id'), table_name='identity')
    op.drop_table('identity')
    op.drop_index(op.f('ix_member_email'), table_name='member')
    op.drop_table('member')
    # ### end Alembic commands ###
