"""model change

Revision ID: 28aa536ee443
Revises: 97fdd1bef659
Created: 2026-08-07 10:20:25.135935+00:00

GENERATED by `alembic revision --autogenerate`. Read it before applying
it — autogenerate is very good at additions and notoriously literal about
renames, which it sees as a DROP and an ADD. Dropping a column takes the
data in it with it.
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '28aa536ee443'
down_revision: Union[str, None] = '97fdd1bef659'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member', sa.Column('can_social', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('member', 'can_social')
    # ### end Alembic commands ###
